// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqsRf4xVbpplfl4WqlGQdvyzfi75hckdc',
    appId: '1:734258626145:android:dc5313969a9390b600f420',
    messagingSenderId: '734258626145',
    projectId: 'studybuddy-4b78f',
    storageBucket: 'studybuddy-4b78f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAVMUA3gYq2_p1e1snzcuEGMI5nahYJdw',
    appId: '1:734258626145:ios:28d961802d80f52600f420',
    messagingSenderId: '734258626145',
    projectId: 'studybuddy-4b78f',
    storageBucket: 'studybuddy-4b78f.appspot.com',
    androidClientId: '734258626145-5lbd7hrra1geuoen1pin3v9qdq8ukomo.apps.googleusercontent.com',
    iosClientId: '734258626145-o79qp3lf79okis97m91md84ms9nsm7nf.apps.googleusercontent.com',
    iosBundleId: 'yxsha.studyBuddy',
  );
}
